name: deploy

on:
  push:
    branches:
      - master

jobs:
  main:
    name: Nx Cloud - Main Job
    uses: nrwl/ci/.github/workflows/nx-cloud-main.yml@v0.4
    with:
      main-branch-name: master
      init-commands: |
        pnpx nx generate @ng-icons/workspace-plugin:svg-to-ts
        pnpx nx generate @ng-icons/workspace-plugin:update-readmes
      parallel-commands: |
        pnpx nx-cloud record -- pnpx nx workspace-lint
        pnpx nx-cloud record -- pnpx nx format:check
      parallel-commands-on-agents: |
        pnpx nx affected --target=lint --parallel=3
        pnpx nx affected --target=test --parallel=3 --ci --code-coverage
        pnpx nx affected --target=build --parallel=3
  agents:
    name: Nx Cloud - Agents
    uses: nrwl/ci/.github/workflows/nx-cloud-agents.yml@v0.4
    with:
      number-of-agents: 3

  # deploy:
  #   name: Deploy
  #   uses: JamesIves/github-pages-deploy-action@4.1.4
  #   with:
  #     branch: gh-pages # The branch the action should deploy to.
  #     folder: dist/apps/documentation # The folder the action should deploy.
