# name: release

# on:
#   release:
#     types:
#       - published

# jobs:
#   main:
#     name: Nx Cloud - Main Job
#     uses: nrwl/ci/.github/workflows/nx-cloud-main.yml@v0.4
#     with:
#       main-branch-name: master
#       init-commands: |
#         yarn generate:iconsets
#         yarn nx workspace-generator update-readmes
#       parallel-commands: |
#         yarn nx-cloud record -- yarn nx workspace-lint
#         yarn nx-cloud record -- yarn nx format:check
#       parallel-commands-on-agents: |
#         yarn nx affected --target=lint --parallel=3
#         yarn nx affected --target=test --parallel=3 --ci --code-coverage
#         yarn nx affected --target=build --parallel=3
#       final-commands: |


#   agents:
#     name: Nx Cloud - Agents
#     uses: nrwl/ci/.github/workflows/nx-cloud-agents.yml@v0.4
#     with:
#       number-of-agents: 3
